"""Rich UI components for Kratos CLI.

Import ``console`` from here — never create a new ``Console()`` directly
in Kratos code, or the Windows encoding fix in :mod:`kratos.ui.theme`
won't apply.
"""
from __future__ import annotations

from .render import (
    coder_header,
    direct_header,
    planner_header,
    print_compress_event,
    print_ctx_bar,
    print_error,
    print_help,
    print_info,
    print_input_separator,
    print_section_time,
    print_success,
    print_usage,
    print_user_msg,
    print_warn,
    relay_header,
    route_info,
    section_banner,
    section_end,
    show_models,
    show_permission_level,
    show_prompts,
    task_summary_panel,
    tool_call,
    user_message_panel,
    verify_header,
)
from .status import (
    _status_line,
    input_capsule,
    print_banner,
    refresh_status,
    status_bar,
)
from .theme import (
    BANNER,
    CODER_COLOR,
    ERROR_COLOR,
    INFO_COLOR,
    LiveBuffer,
    PLANNER_COLOR,
    SUCCESS_COLOR,
    WARN_COLOR,
    _fmt_time,
    _k_tokens,
    _PERM_COLOR,
    _PERM_COLORS,
    _PERM_LABEL,
    _ROLE_ICON,
    _ROLE_STYLE,
    _short_model,
    _tok_short,
    console,
    elapsed_str,
)

__all__ = [
    "console",
    "BANNER",
    "PLANNER_COLOR",
    "CODER_COLOR",
    "ERROR_COLOR",
    "INFO_COLOR",
    "SUCCESS_COLOR",
    "WARN_COLOR",
    "LiveBuffer",
    "elapsed_str",
    "print_banner",
    "refresh_status",
    "status_bar",
    "input_capsule",
    "planner_header",
    "coder_header",
    "verify_header",
    "relay_header",
    "section_end",
    "route_info",
    "tool_call",
    "direct_header",
    "print_error",
    "print_success",
    "print_info",
    "print_warn",
    "print_ctx_bar",
    "print_compress_event",
    "print_section_time",
    "print_user_msg",
    "print_input_separator",
    "print_help",
    "show_permission_level",
    "print_usage",
    "show_models",
    "show_prompts",
    "user_message_panel",
    "task_summary_panel",
    "section_banner",
]
